{% set name = "cni" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/containernetworking/{{ name }}/archive/v{{ version }}.tar.gz
  fn: {{ name }}-{{ version }}.tar.gz  # [not win]
  sha256: 4517eabfd65aea2012dc48d057bf889a0a41ed9837387d95cd1e36c0dbddcfd4

build:
  skip: True  # [not linux]
  number: 0

requirements:
  build:
    - {{ compiler('go') }}
    - {{ compiler('c') }}
    - make
  host:
    - go
  run:
    - jq

test:
  commands:
    - which cnitool

about:
  home: https://github.com/containernetworking/cni
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: CNI is a specification and libraries for writing plugins to configure network interfaces in Linux containers.
  dev_url: https://github.com/containernetworking/cni

extra:
  recipe-maintainers:
    - sodre
    - adbeda
