{% set name = "cni" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/containernetworking/{{ name }}/archive/v{{ version }}.tar.gz
  fn: {{ name }}-{{ version }}.tar.gz  # [not win]
  sha256: 78d57477d6b0ab9dc4d75ce9f275302d2f379206b5326503e57d9c08b76484c1

build:
  skip: True  # [not linux]
  number: 0

requirements:
  build:
    - {{ compiler('go') }}
    - {{ compiler('c') }}
    - make
  host:
  run:
    - jq

test:
  commands:
    - which cnitool

about:
  home: https://github.com/containernetworking/cni
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: CNI is a specification and libraries for writing plugins to configure network interfaces in Linux containers.
  dev_url: https://github.com/containernetworking/cni

extra:
  recipe-maintainers:
    - sodre
