{% set import_path = "github.com/containernetworking/cni" %}
{% set version = "1.1.1" %}

{% set name = import_path.split('/')[-1] %}
{% set pkg_src = ('src/' + import_path).replace("/", os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  folder: {{ pkg_src }}
  url: https://{{ import_path }}/archive/v{{ version }}.tar.gz
  sha256: f95a0a9aa7e142982a1cae28ffb210aaf2b423e597c1a0305f50e82942dbb86e

build:
  skip: true  # [not linux]
  number: 0
  script:
    - pushd {{ pkg_src }}
    - go get -d -v ./libcni
    - go install ./cnitool

requirements:
  build:
    - {{ compiler('go') }}
    - {{ compiler('c') }}

  run:
    - jq

test:
  commands:
    - which cnitool

about:
  home: https://github.com/containernetworking/cni
  license: Apache-2.0
  license_family: Apache
  license_file: {{ pkg_src }}/LICENSE
  summary: CNI is a specification and libraries for writing plugins to configure network interfaces in Linux containers.
  dev_url: https://github.com/containernetworking/cni

extra:
  recipe-maintainers:
    - mxr-conda
    - sodre
    - adbeda
    - rluria14
    - oblute
